name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          cd src/
          python -m unittest discover -s tests/

          
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 23.23.125.33
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
              rm -rf T2A3
              git clone https://github.com/jodiefostersarmy/T2A3.git
              python3.8 -m venv/github-actions/T2A3/venv
              pip3 install -r T2A3/requirements.txt